### model
model_name_or_path: Qwen/Qwen1.5-MoE-A2.7B
trust_remote_code: true
quantization_bit: 4
quantization_method: bnb
double_quantization: true
flash_attn: disabled
use_v1_kernels: false
moe_aux_loss_coef: 0.001

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target: gate_proj,up_proj,down_proj,gate,shared_expert_gate

### dataset
dataset_dir: ../data/train
dataset: FME_26B_traindata
template: qwen
cutoff_len: 1024
max_samples: 128
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 2
packing: false

### output
output_dir: saves/qwen1.5-moe-a2.7b/qlora/moe_test_20260701_1824
logging_steps: 1
save_steps: 10
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
max_steps: 10
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
fp16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
