### model
model_name_or_path: Qwen/Qwen3.6-27B
trust_remote_code: true
use_v1_kernels: false
flash_attn: disabled

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
deepspeed: examples/deepspeed/ds_z3_npu_lora_config.json

### dataset
dataset_dir: ../data/train
dataset: FME_26B_traindata
template: qwen3_6
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
packing: false

### output
output_dir: saves/qwen3.6-27b/lora/sft_20260701_1433
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.01
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
